-- Migration: Create sessions table
-- Description: Session management table with automatic expiration tracking
-- Author: DatabaseArchitect
-- Date: 2025-12-11

-- Create sessions table (idempotent)
CREATE TABLE IF NOT EXISTS sessions (
  -- Primary key - random session ID generated by application (Oslo)
  id TEXT PRIMARY KEY,

  -- Foreign key to users
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Session expiration and metadata
  expires_at TIMESTAMPTZ NOT NULL,
  ip_address TEXT,
  user_agent TEXT,

  -- Timestamp
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for fast lookups (idempotent)
-- Index for finding all sessions for a user
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);

-- Index for finding expired sessions (cleanup queries)
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);

-- Composite index for user + expiration queries (finding valid sessions for a user)
CREATE INDEX IF NOT EXISTS idx_sessions_user_expires ON sessions(user_id, expires_at);

-- Comments for documentation
COMMENT ON TABLE sessions IS 'User session storage with expiration tracking';
COMMENT ON COLUMN sessions.id IS 'Primary key - random session ID generated by Oslo';
COMMENT ON COLUMN sessions.user_id IS 'Foreign key to users table - cascades on delete';
COMMENT ON COLUMN sessions.expires_at IS 'Timestamp when session expires - used for validation';
COMMENT ON COLUMN sessions.ip_address IS 'IP address of the client that created the session';
COMMENT ON COLUMN sessions.user_agent IS 'User agent string of the client that created the session';
COMMENT ON COLUMN sessions.created_at IS 'Timestamp when session was created';

-- Note: Session expiration is handled in application logic, not via PostgreSQL TTL
-- The expires_at column is checked during session validation
-- A background cleanup job should periodically delete expired sessions
