-- Migration: Create email_verification_tokens table
-- Description: Email verification tokens for confirming user email addresses
-- Author: DatabaseArchitect
-- Date: 2025-12-11

-- Create email_verification_tokens table (idempotent)
CREATE TABLE IF NOT EXISTS email_verification_tokens (
  -- Primary key - random token generated by application (Oslo)
  token TEXT PRIMARY KEY,

  -- Foreign key to users
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Email being verified (may differ from current user.email during email change)
  email TEXT NOT NULL,

  -- Token expiration (typically 24 hours)
  expires_at TIMESTAMPTZ NOT NULL,

  -- Timestamp
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for fast lookups (idempotent)
-- Index for finding all verification tokens for a user
CREATE INDEX IF NOT EXISTS idx_email_verification_user_id ON email_verification_tokens(user_id);

-- Index for finding expired tokens (cleanup queries)
CREATE INDEX IF NOT EXISTS idx_email_verification_expires_at ON email_verification_tokens(expires_at);

-- Comments for documentation
COMMENT ON TABLE email_verification_tokens IS 'Email verification tokens for confirming user email addresses';
COMMENT ON COLUMN email_verification_tokens.token IS 'Primary key - random verification token generated by Oslo';
COMMENT ON COLUMN email_verification_tokens.user_id IS 'Foreign key to users table - cascades on delete';
COMMENT ON COLUMN email_verification_tokens.email IS 'Email address being verified - may differ from user.email during email change';
COMMENT ON COLUMN email_verification_tokens.expires_at IS 'Timestamp when token expires - typically 24 hours from creation';
COMMENT ON COLUMN email_verification_tokens.created_at IS 'Timestamp when token was created';

-- Note: Expired tokens should be periodically cleaned up by a background job
-- Tokens are single-use and should be deleted after successful verification
