-- Migration: Create password_reset_tokens table
-- Description: Password reset tokens for secure password recovery flow
-- Author: DatabaseArchitect
-- Date: 2025-12-11

-- Create password_reset_tokens table (idempotent)
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  -- Primary key - random token generated by application (Oslo)
  token TEXT PRIMARY KEY,

  -- Foreign key to users
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Token expiration (typically 1 hour for security)
  expires_at TIMESTAMPTZ NOT NULL,

  -- Timestamp
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for fast lookups (idempotent)
-- Index for finding all reset tokens for a user
CREATE INDEX IF NOT EXISTS idx_password_reset_user_id ON password_reset_tokens(user_id);

-- Index for finding expired tokens (cleanup queries)
CREATE INDEX IF NOT EXISTS idx_password_reset_expires_at ON password_reset_tokens(expires_at);

-- Comments for documentation
COMMENT ON TABLE password_reset_tokens IS 'Password reset tokens for secure password recovery flow';
COMMENT ON COLUMN password_reset_tokens.token IS 'Primary key - random reset token generated by Oslo';
COMMENT ON COLUMN password_reset_tokens.user_id IS 'Foreign key to users table - cascades on delete';
COMMENT ON COLUMN password_reset_tokens.expires_at IS 'Timestamp when token expires - typically 1 hour for security';
COMMENT ON COLUMN password_reset_tokens.created_at IS 'Timestamp when token was created';

-- Note: Reset tokens should have short expiration times (1 hour) for security
-- Tokens are single-use and should be deleted after successful password reset
-- When a user requests a new reset token, old tokens should be invalidated/deleted
-- Expired tokens should be periodically cleaned up by a background job
