/**
 * Database Schema Types
 *
 * TypeScript interfaces and Kysely types for the mech-auth database schema.
 * These types must match the SQL schema defined in the migration files.
 *
 * @see /migrations/001_create_users_table.sql
 * @see /migrations/002_create_sessions_table.sql
 * @see /migrations/003_create_verification_tokens.sql
 * @see /migrations/004_create_reset_tokens.sql
 */

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/**
 * Users Table
 *
 * Core users table with support for email/password and OAuth authentication.
 */
export interface UsersTable {
  id: ColumnType<string, string | undefined, never> // UUID, generated on insert
  email: string
  email_verified: ColumnType<boolean, boolean | undefined, boolean> // Default: false
  password_hash: string | null // NULL for OAuth-only users

  // OAuth provider IDs
  github_id: string | null
  google_id: string | null

  // User profile
  name: string | null
  avatar_url: string | null

  // Timestamps
  created_at: ColumnType<Date, Date | undefined, never> // Default: NOW()
  updated_at: ColumnType<Date, Date | undefined, Date> // Auto-updated via trigger
}

/**
 * Sessions Table
 *
 * Session management with expiration tracking.
 * Session IDs are generated by the application using Oslo.
 */
export interface SessionsTable {
  id: string // Random session ID (generated by Oslo)
  user_id: string // UUID foreign key to users
  expires_at: Date
  ip_address: string | null
  user_agent: string | null
  created_at: ColumnType<Date, Date | undefined, never> // Default: NOW()
}

/**
 * Email Verification Tokens Table
 *
 * Tokens for email verification flow.
 * Typically expire after 24 hours.
 */
export interface EmailVerificationTokensTable {
  token: string // Random token (generated by Oslo)
  user_id: string // UUID foreign key to users
  email: string // Email being verified
  expires_at: Date
  created_at: ColumnType<Date, Date | undefined, never> // Default: NOW()
}

/**
 * Password Reset Tokens Table
 *
 * Tokens for password reset flow.
 * Typically expire after 1 hour for security.
 */
export interface PasswordResetTokensTable {
  token: string // Random token (generated by Oslo)
  user_id: string // UUID foreign key to users
  expires_at: Date
  created_at: ColumnType<Date, Date | undefined, never> // Default: NOW()
}

/**
 * Database Schema
 *
 * Complete database schema for Kysely type-safe queries.
 */
export interface Database {
  users: UsersTable
  sessions: SessionsTable
  email_verification_tokens: EmailVerificationTokensTable
  password_reset_tokens: PasswordResetTokensTable
}

/**
 * Type-safe row types for SELECT queries
 */
export type User = Selectable<UsersTable>
export type Session = Selectable<SessionsTable>
export type EmailVerificationToken = Selectable<EmailVerificationTokensTable>
export type PasswordResetToken = Selectable<PasswordResetTokensTable>

/**
 * Type-safe input types for INSERT queries
 */
export type NewUser = Insertable<UsersTable>
export type NewSession = Insertable<SessionsTable>
export type NewEmailVerificationToken = Insertable<EmailVerificationTokensTable>
export type NewPasswordResetToken = Insertable<PasswordResetTokensTable>

/**
 * Type-safe input types for UPDATE queries
 */
export type UserUpdate = Updateable<UsersTable>
export type SessionUpdate = Updateable<SessionsTable>
export type EmailVerificationTokenUpdate = Updateable<EmailVerificationTokensTable>
export type PasswordResetTokenUpdate = Updateable<PasswordResetTokensTable>

/**
 * User with session information (common join result)
 */
export interface UserWithSession {
  user: User
  session: Session
}

/**
 * Public user profile (safe to expose to client)
 */
export interface PublicUser {
  id: string
  email: string
  email_verified: boolean
  name: string | null
  avatar_url: string | null
  created_at: Date
}

/**
 * Session with user information (common join result)
 */
export interface SessionWithUser {
  session: Session
  user: PublicUser
}

/**
 * Helper function to convert User to PublicUser
 */
export function toPublicUser(user: User): PublicUser {
  return {
    id: user.id,
    email: user.email,
    email_verified: user.email_verified,
    name: user.name,
    avatar_url: user.avatar_url,
    created_at: user.created_at,
  }
}

/**
 * Type guards
 */
export function isValidSession(session: Session): boolean {
  return new Date(session.expires_at) > new Date()
}

export function isValidEmailVerificationToken(token: EmailVerificationToken): boolean {
  return new Date(token.expires_at) > new Date()
}

export function isValidPasswordResetToken(token: PasswordResetToken): boolean {
  return new Date(token.expires_at) > new Date()
}
